export const items = {
  recommendItems : [
    {
      id: 'item000001',
      brandName: 'BRAND_NAME1',
      itemName: '차량용 강아지 방석',
      price: 129000,
      imgUrl: ''
    },
    {
      id: 'item000002',
      brandName: 'BRAND_NAME2',
      itemName: '고급 케이지 ',
      price: 219000,
      imgUrl: ''
    },
    {
      id: 'item000003',
      brandName: 'BRAND_NAME3',
      itemName: '대형견 에티켓 넥카라',
      price: 12000,
      imgUrl: ''
    },
    {
      id: 'item000004',
      brandName: 'BRAND_NAME4',
      itemName: '강아지/고양이 공용 수제 간식',
      price: 49000,
      imgUrl: ''
    },
    {
      id: 'item000005',
      brandName: 'BRAND_NAME5',
      itemName: '산책 줄 마우스 마스크',
      price: 129000,
      imgUrl: ''
    },
  ],
  recommendHospitals : [
    {
      id: 'hospital01',
      place: '위치1',
      name: '월드펫동물종합병원',
      score: 4.7,
      reviews: 99,
      imgUrl: ''
    },
    {
      id: 'hospital02',
      place: '위치2',
      name: '펫러브동물병원',
      score: 4.7,
      reviews: 99,
      imgUrl: ''
    },
    {
      id: 'hospital03',
      place: '위치3',
      name: '24시응급펫센터',
      score: 4.7,
      reviews: 99,
      imgUrl: ''
    },
    {
      id: 'hospital04',
      place: '위치4',
      name: '강아지동물병원',
      score: 4.7,
      reviews: 99,
      imgUrl: ''
    },
    {
      id: 'hospital05',
      place: '위치5',
      name: '고양이종합병원',
      score: 4.7,
      reviews: 99,
      imgUrl: ''
    },
  ],
  hotItems : [
    {
      id: 'hot0000001',
      brandName: 'BRAND_NAME1',
      itemName: '차량용 강아지 방석',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hot0000002',
      brandName: 'BRAND_NAME2',
      itemName: '고급 케이지 ',
      price: 219000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hot0000003',
      brandName: 'BRAND_NAME3',
      itemName: '대형견 에티켓 넥카라',
      price: 12000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hot0000004',
      brandName: 'BRAND_NAME4',
      itemName: '강아지/고양이 공용 수제 간식',
      price: 49000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hot0000005',
      brandName: 'BRAND_NAME5',
      itemName: '산책 줄 마우스 마스크',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hot0000006',
      brandName: 'BRAND_NAME6',
      itemName: '휴대용 배변패드',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hot0000007',
      brandName: 'BRAND_NAME7',
      itemName: '산책용 물그릇',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
  ],
  newItems : [
    {
      id: 'new0000001',
      brandName: 'BRAND_NAME1',
      itemName: '차량용 강아지 방석',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000002',
      brandName: 'BRAND_NAME2',
      itemName: '고급 케이지 ',
      price: 219000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000003',
      brandName: 'BRAND_NAME3',
      itemName: '대형견 에티켓 넥카라',
      price: 12000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000004',
      brandName: 'BRAND_NAME4',
      itemName: '강아지/고양이 공용 수제 간식',
      price: 49000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000005',
      brandName: 'BRAND_NAME5',
      itemName: '산책 줄 마우스 마스크',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000006',
      brandName: 'BRAND_NAME6',
      itemName: '휴대용 배변패드',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000007',
      brandName: 'BRAND_NAME7',
      itemName: '산책용 물그릇',
      price: 129000,
      imgUrl: '',
      score: 4.7,
      reviews: 99,
    },
  ],
}
