export const items = {
  recommendItems : [
    {
      id: 'item000001',
      brandName: 'BRAND_NAME1',
      itemName: '쿠키모양 수제 간식',
      price: 129000,
      imgUrl: 'snack1.jpg'
    },
    {
      id: 'item000002',
      brandName: 'BRAND_NAME2',
      itemName: '강아지용 스틱 스낵 ',
      price: 219000,
      imgUrl: 'snack2.jpg'
    },
    {
      id: 'item000003',
      brandName: 'BRAND_NAME3',
      itemName: '과일맛 애견 캔디',
      price: 12000,
      imgUrl: 'snack3.jpg'
    },
    {
      id: 'item000004',
      brandName: 'BRAND_NAME4',
      itemName: '애견/애묘 공용 통조림',
      price: 49000,
      imgUrl: 'snack4.jpg'
    },
    {
      id: 'item000005',
      brandName: 'BRAND_NAME5',
      itemName: '애견/애묘 통조림 미니',
      price: 129000,
      imgUrl: 'snack5.jpg'
    },
  ],
  recommendHospitals : [
    {
      id: 'hospital01',
      place: '위치1',
      name: '월드펫동물종합병원',
      score: 4.7,
      reviews: 99,
      imgUrl: 'care1.jpg'
    },
    {
      id: 'hospital02',
      place: '위치2',
      name: '펫러브동물병원',
      score: 4.7,
      reviews: 99,
      imgUrl: 'care2.jpg'
    },
    {
      id: 'hospital03',
      place: '위치3',
      name: '24시응급펫센터',
      score: 4.7,
      reviews: 99,
      imgUrl: 'care3.jpg'
    },
    {
      id: 'hospital04',
      place: '위치4',
      name: '강아지동물병원',
      score: 4.7,
      reviews: 99,
      imgUrl: 'care4.jpg'
    },
    {
      id: 'hospital05',
      place: '위치5',
      name: '고양이종합병원',
      score: 4.7,
      reviews: 99,
      imgUrl: 'care5.jpg'
    },
  ],
  hotItems : [
    {
      id: 'hotItems0000001',
      brandName: 'BRAND_NAME1',
      itemName: '5가지 믹스 사료',
      price: 129000,
      imgUrl: 'meal6.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotItems0000002',
      brandName: 'BRAND_NAME2',
      itemName: '대형견 닭고기 사료 ',
      price: 219000,
      imgUrl: 'meal2.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotItems0000003',
      brandName: 'BRAND_NAME3',
      itemName: '비건 콩고기 사료',
      price: 12000,
      imgUrl: 'meal3.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotItems0000004',
      brandName: 'BRAND_NAME4',
      itemName: '8가지 믹스 + 그릇 증정',
      price: 49000,
      imgUrl: 'meal7.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotItems0000005',
      brandName: 'BRAND_NAME5',
      itemName: '연어맛 오메가3 사료',
      price: 129000,
      imgUrl: 'meal9.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotItems0000006',
      brandName: 'BRAND_NAME6',
      itemName: '휴대용 봉지 사료 파우치',
      price: 129000,
      imgUrl: 'meal8.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotItems0000007',
      brandName: 'BRAND_NAME7',
      itemName: '소형견 믹스 사료',
      price: 129000,
      imgUrl: 'meal1.jpg',
      score: 4.7,
      reviews: 99,
    },
  ],
  newItems : [
    {
      id: 'new0000001',
      brandName: 'BRAND_NAME1',
      itemName: '롤리폴리 개껌 스틱',
      price: 129000,
      imgUrl: 'snack8.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000002',
      brandName: 'BRAND_NAME2',
      itemName: '강아지용 스틱 하드 ',
      price: 219000,
      imgUrl: 'snack2.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000003',
      brandName: 'BRAND_NAME3',
      itemName: '과일맛 애견 캔디',
      price: 12000,
      imgUrl: 'snack3.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000004',
      brandName: 'BRAND_NAME4',
      itemName: '애견/애묘 공용 통조림',
      price: 49000,
      imgUrl: 'snack4.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000005',
      brandName: 'BRAND_NAME5',
      itemName: '고양이 통조림 미니',
      price: 129000,
      imgUrl: 'snack5.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000006',
      brandName: 'BRAND_NAME6',
      itemName: '뼈다귀 쿠키모양 라지',
      price: 129000,
      imgUrl: 'snack6.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'new0000007',
      brandName: 'BRAND_NAME7',
      itemName: '뼈다귀 쿠키모양 스몰',
      price: 129000,
      imgUrl: 'snack7.jpg',
      score: 4.7,
      reviews: 99,
    },
  ],
  hospital : [
    {
      id: 'hospital1',
      brandName: 'BRAND_NAME1',
      itemName: '롤리폴리 개껌 스틱',
      price: 129000,
      imgUrl: 'care1.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hospital2',
      brandName: 'BRAND_NAME2',
      itemName: '강아지용 스틱 하드 ',
      price: 219000,
      imgUrl: 'care2.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hospital3',
      brandName: 'BRAND_NAME3',
      itemName: '과일맛 애견 캔디',
      price: 12000,
      imgUrl: 'care3.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hospital4',
      brandName: 'BRAND_NAME4',
      itemName: '애견/애묘 공용 통조림',
      price: 49000,
      imgUrl: 'care4.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hospital5',
      brandName: 'BRAND_NAME4',
      itemName: '애견/애묘 공용 통조림',
      price: 49000,
      imgUrl: 'care5.jpg',
      score: 4.7,
      reviews: 99,
    },
  ],
  beauty : [
    {
      id: 'beauty1',
      brandName: 'BRAND_NAME1',
      itemName: '뽀삐 미용실',
      price: 129000,
      imgUrl: 'beauty1.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'beauty2',
      brandName: 'BRAND_NAME2',
      itemName: '돈바이트 애견미용',
      price: 219000,
      imgUrl: 'beauty2.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'beauty3',
      brandName: 'BRAND_NAME3',
      itemName: '곰돌이미용 전문',
      price: 12000,
      imgUrl: 'beauty3.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'beauty4',
      brandName: 'BRAND_NAME4',
      itemName: '미용+프로필촬영 패키지',
      price: 49000,
      imgUrl: 'beauty4.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'beauty5',
      brandName: 'BRAND_NAME5',
      itemName: '손톱/모질 개선 케어',
      price: 129000,
      imgUrl: 'beauty5.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'beauty6',
      brandName: 'BRAND_NAME6',
      itemName: '미용카페',
      price: 129000,
      imgUrl: 'beauty6.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'beauty7',
      brandName: 'BRAND_NAME7',
      itemName: '1인 전문 미용',
      price: 129000,
      imgUrl: 'beauty7.jpg',
      score: 4.7,
      reviews: 99,
    },
  ],
  hotel : [
    {
      id: 'hotel1',
      brandName: 'BRAND_NAME1',
      itemName: '써니도그하우스',
      price: 129000,
      imgUrl: 'hotel1.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotel2',
      brandName: 'BRAND_NAME2',
      itemName: '정글독 놀이터',
      price: 219000,
      imgUrl: 'hotel2.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotel3',
      brandName: 'BRAND_NAME3',
      itemName: '개트럴파크',
      price: 12000,
      imgUrl: 'hotel3.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotel4',
      brandName: 'BRAND_NAME4',
      itemName: '모던 도그호텔',
      price: 49000,
      imgUrl: 'hotel4.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotel5',
      brandName: 'BRAND_NAME5',
      itemName: '코지하우스',
      price: 129000,
      imgUrl: 'hotel5.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotel6',
      brandName: 'BRAND_NAME6',
      itemName: '럭셔리 2성호텔',
      price: 129000,
      imgUrl: 'hotel6.jpg',
      score: 4.7,
      reviews: 99,
    },
    {
      id: 'hotel7',
      brandName: 'BRAND_NAME7',
      itemName: '프라이빗 1인실 제공',
      price: 129000,
      imgUrl: 'hotel7.jpg',
      score: 4.7,
      reviews: 99,
    },
  ],
}
